import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactQueryProvider from "@/libs/ReactQueryProvider";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/navbar";
import "../styles/index.scss";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <ReactQueryProvider>
          <main>{children}</main>
          <ToastContainer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
